apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  container: 
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1